using UnityEngine;

namespace SideXP.Core
{

    /// <summary>
    /// <para>
    /// Marks a field as a container for a unique id.
    /// </para>
    /// <para>
    /// If used in an asset script (likely <see cref=ScriptableObject"/>), the property will contain the GUID of the asset as generated by
    /// Unity. Note that this will work effectively only on assets saved on disk.
    /// </para>
    /// <para>
    /// If the previous case is not applicable and this attribute is used on a strng property, it will contain a native C# GUID. For an
    /// integer or float property, it will contain the hash code of a native C# GUID.
    /// </para>
    /// </summary>
    /// <remarks>You should use this attribute in addition with <see cref="SerializeField"/>, and
    /// <see cref="HideInInspector"/> or <see cref="ReadonlyAttribute"/> in order to make the field readonly.</remarks>
    public class UniqueIdAttribute : PropertyAttribute { }

}