using System;
using System.CodeDom;
using System.IO;
using System.Reflection;

using NUnit.Framework;

using SideXP.Core.EditorOnly;

namespace SideXP.Core.Tests
{

    public class CodeGenerationUtilityTests
    {

        // Absolute path written by a GenerateScriptFile test, deleted on teardown.
        private string _generatedFilePath;

        [TearDown]
        public void TearDown()
        {
            if (!string.IsNullOrEmpty(_generatedFilePath) && File.Exists(_generatedFilePath))
                File.Delete(_generatedFilePath);
            _generatedFilePath = null;
        }

        // Builds a minimal compile unit: one namespace containing one public class.
        private static CodeCompileUnit MakeSampleUnit(string namespaceName, string className)
        {
            var unit = new CodeCompileUnit();
            var ns = new CodeNamespace(namespaceName);
            unit.Namespaces.Add(ns);
            ns.Types.Add(new CodeTypeDeclaration(className)
            {
                IsClass = true,
                TypeAttributes = TypeAttributes.Public,
            });
            return unit;
        }

        #region MakeScriptCompileUnit

        [Test]
        public void MakeScriptCompileUnit_NoType_DomEqualsImports()
        {
            CodeCompileUnit unit = CodeGenerationUtility.MakeScriptCompileUnit(out CodeNamespace imports, out CodeNamespace dom);
            Assert.IsNotNull(imports);
            Assert.AreSame(imports, dom, "without a related type, the DOM namespace is the imports namespace");
            Assert.AreEqual(1, unit.Namespaces.Count);
        }

        [Test]
        public void MakeScriptCompileUnit_TypeWithNamespace_AddsSeparateDomNamespace()
        {
            CodeCompileUnit unit = CodeGenerationUtility.MakeScriptCompileUnit(typeof(CodeGenerationUtilityTests), out CodeNamespace imports, out CodeNamespace dom);
            Assert.AreNotSame(imports, dom);
            Assert.AreEqual(typeof(CodeGenerationUtilityTests).Namespace, dom.Name);
            Assert.AreEqual(2, unit.Namespaces.Count);
            Assert.Contains(imports, unit.Namespaces);
            Assert.Contains(dom, unit.Namespaces);
        }

        #endregion


        #region GenerateScript

        [Test]
        public void GenerateScript_EmitsNamespaceAndClass()
        {
            string script = CodeGenerationUtility.GenerateScript(MakeSampleUnit("MyGenerated", "MyClass"));
            StringAssert.Contains("namespace MyGenerated", script);
            StringAssert.Contains("class MyClass", script);
        }

        [Test]
        public void GenerateScript_StripsAutoGeneratedComment()
        {
            string script = CodeGenerationUtility.GenerateScript(MakeSampleUnit("MyGenerated", "MyClass"));
            Assert.IsFalse(script.Contains("auto-generated"), "the CodeDom auto-generated header must be removed");
            Assert.IsFalse(script.Contains("//----"), "the header's dashed separators must be removed");
        }

        [Test]
        public void GenerateScript_UsesFourSpaceIndentation()
        {
            // The namespace's content is indented one level; with IndentString = "    " that's exactly four spaces.
            string script = CodeGenerationUtility.GenerateScript(MakeSampleUnit("MyGenerated", "MyClass"));
            StringAssert.Contains("    public class MyClass", script);
        }

        #endregion


        #region RemoveAutocomment

        [Test]
        public void RemoveAutocomment_RemovesHeaderBlock()
        {
            string content =
                "//------------------------------------------------------------------------------\n" +
                "// <auto-generated>\n" +
                "//     This code was generated by a tool.\n" +
                "// </auto-generated>\n" +
                "//------------------------------------------------------------------------------\n" +
                "namespace Foo { }";

            CodeGenerationUtility.RemoveAutocomment(ref content);

            Assert.IsFalse(content.Contains("auto-generated"));
            Assert.IsFalse(content.Contains("//----"));
            StringAssert.StartsWith("namespace Foo", content);
        }

        [Test]
        public void RemoveAutocomment_NoHeader_LeavesContentUntouched()
        {
            string content = "namespace Foo { }";
            CodeGenerationUtility.RemoveAutocomment(ref content);
            Assert.AreEqual("namespace Foo { }", content);
        }

        #endregion


        #region FixBlankLines

        [Test]
        public void FixBlankLines_CollapsesExcessBlankLines()
        {
            string content = "a\n\n\n\n\nb";
            CodeGenerationUtility.FixBlankLines(ref content);
            Assert.AreEqual($"a{Environment.NewLine}{Environment.NewLine}b", content, "3+ blank lines collapse to a single blank line");
        }

        [Test]
        public void FixBlankLines_KeepsSingleBlankLine()
        {
            // A single blank line (two line breaks) is below the {3,} threshold and must be preserved.
            string content = "a\n\nb";
            CodeGenerationUtility.FixBlankLines(ref content);
            Assert.AreEqual("a\n\nb", content);
        }

        [Test]
        public void FixBlankLines_SeparatesConsecutiveClosingBrackets()
        {
            string content = "}\n}";
            CodeGenerationUtility.FixBlankLines(ref content);
            Assert.AreEqual($"}}{Environment.NewLine}{Environment.NewLine}}}", content, "consecutive closing brackets get a blank line between them");
        }

        #endregion


        #region GenerateScriptFile

        [Test]
        public void GenerateScriptFile_WritesSameContentAsGenerateScript()
        {
            CodeCompileUnit unit = MakeSampleUnit("MyGenerated", "MyClass");
            string tempPath = Path.Combine(Path.GetTempPath(), "sidexp_codegen_" + Guid.NewGuid().ToString("N") + ".cs");
            // GenerateScriptFile normalizes the path through ToAbsolutePath; track the same value for reading/cleanup.
            _generatedFilePath = PathUtility.ToAbsolutePath(tempPath);

            bool success = CodeGenerationUtility.GenerateScriptFile(tempPath, unit);

            Assert.IsTrue(success);
            Assert.IsTrue(File.Exists(_generatedFilePath));
            Assert.AreEqual(CodeGenerationUtility.GenerateScript(unit), File.ReadAllText(_generatedFilePath));
        }

        #endregion

    }

}
